# Generated by Django 3.2.7 on 2021-09-03 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='date_Posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
