# Generated by Django 3.2.7 on 2021-09-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profie_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='pics'),
        ),
    ]
